name: Archive File

on:
  push:
    branches:
      - dwayne-ci
    paths-ignore:
        - .github/**
jobs:
  Archive:
    name: Archive Files
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build app
      uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: Install dependencies
      run: npm ci
      working-directory: my-app
    
    - name: Build app
      run: npm run build
      working-directory: my-app

    - name: Archive Build Files
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: my-app/dist/
        retention-days: 2
